### ISSUE TITLE
please freeze cells

### ISSUE THREAD

**Issue by peratik** [pocketjoso/sudokuJS#3]
like this

```
$('.sudoku-board-cell').each(function(){
   var cell = $(this).find('input');
   if (parseInt(cell.attr('value'))>0) cell.attr('disabled','disabled');
});
```

**Comment by pocketjoso** [comment]
Then you cannot edit mistakes, hence I don't want this to be built into the library.

It's easy to setup yourself. You can use the [boardupdatedfn callback](https://github.com/pocketjoso/sudokuJS#boardupdatedfn) to handle disabling the `data.cellsUpdated`, perhaps just when `data.cause === 'user input'`.

Feel free to continue to comment.
