### ISSUE TITLE
Solving/Checking sudoku correctness 

### ISSUE THREAD

**Issue by krizajb** [pocketjoso/sudokuJS#4]
Hi,
I was wondering how come you are solving the sudoku while you already generated all results at the start? I am trying to implement a check function, which If i understand correctly just compares input values with $board values, or am I missing something? Is it maybe for users who are passing the board on their own?

PS: Dunno how to mark this "issue" as a question :)

**Comment by pocketjoso** [comment]
Hi,
Did you see the [analyzing-the-board](https://github.com/pocketjoso/sudokuJS#analyzing-the-board) section? It shows how to "check" the board for errors etc.

Does this answer your question?

**Comment by krizajb** [comment]
Thanks for quick reply. Hmm ... My check needs to update the UI, marking wrong cells with a frame or background. If I'm not mistaken analyzeBoard doesn't return correctness info for each cell? And I still think that for my case solving the sudoku rather then comparing current value with board values is a bit of overhead. So would my "custom" check comparing current value with board value be sufficient or are there any concerns? I am intending to use auto generated board all the time.

**Comment by pocketjoso** [comment]
I'm sorry I missed to answer this question before. By now it's been such a long time, I hope you found a way forward on your own. If you still need help, please let me know and I'll do my best - if so we can re-open this question.
