### ISSUE TITLE
How to start solving generated sudoku again?

### ISSUE THREAD

**Issue by vsevjednom-cz** [pocketjoso/sudokuJS#7]
I've got one little question. I want start solving again some sudoku. I'm triying to add button "Again" with delete all values in "highlight-val" classes - that's ok but script still thinks that there are values in these cells.
So how to delete "highlight-val" values and tell the script that these cells are empty?

**Comment by vsevjednom-cz** [comment]
Hmm, I found `getBoard`/`setBoard`. It works but it can reload sudoku only once. There's an empty array after `setBoard(originalBoard);`.

**Comment by vsevjednom-cz** [comment]
Weird solution. I must create two variables:
```
    var originalBoard = trimBoard(mySudokuJS.getBoard());
    var originalBoard1 = trimBoard(mySudokuJS.getBoard());
```
Function `trimBoard` copied from #1 
... and using first variable for first `setBoard` and second variable for second `setBoard`... And I must do this:
```
$startAgain.on("click", function(){
...
var originalBoard1=trimBoard(mySudokuJS.getBoard());
originalBoard=originalBoard1;
...
}
```

**Comment by pocketjoso** [comment]
Let me see if I’ve understood you: are you trying to reset your board back to how it was originally, when it was first generated? If that’s the case, I think it should work if you use `getBoard` directly after the board was generated, save it to a variable, and then use `setBoard` with that variable when you want to reset. Is that what you tried already?

**Comment by vsevjednom-cz** [comment]
> back to how it was originally, when it was first generated

Yes 🥳.



> if you use `getBoard` directly after the board was generated, save it to a variable, and then use `setBoard` with that variable when you want to reset. Is that what you tried already?

That's what I'm doing but it works only once. I'm using for example `var originalBoard = trimBoard(mySudokuJS.getBoard());`. But there's an empty array in this variable after `setBoard(originalBoard);` - so original content in the variable `originalBoard` doesn't stay, I don't know why.

**Comment by pocketjoso** [comment]
Aha. It must be because the library mutates your array. It should work
for you then if you clone the array, using Array.slice:
> originalBoard = mySudokuJS.getBoard().slice()

Trimming is not necessary. Let me know if this solves your issue!

On February 21, 2022, Github ***@***.***> wrote:
> > back to how it was originally, when it was first generated
> >
>
> Yes 🥳.
>
> > if you use getBoard directly after the board was generated, save it
> > to a variable, and then use setBoard with that variable when you
> > want to reset. Is that what you tried already?
> >
>
> That's what I'm doing but it works only once. I'm using for example
> var originalBoard = trimBoard(mySudokuJS.getBoard());. But there's an
> empty array in this variable after setBoard(originalBoard); - so
> original content in the variable originalBoard doesn't stay, I don't
> know why.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pocketjoso/sudokuJS/issues/7#issuecomment-
1046312323>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABW4CADKFCWUKNF7PISS2OLU4FDTFANCNFSM5O4CM7FQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you commented.Message ID:
***@***.***>

**Comment by vsevjednom-cz** [comment]
Thank you but same problem. `slice` doesn't change anything.

**Comment by vsevjednom-cz** [comment]
It doesn't matter, my weird solution works.
But I've got last question: I want to create url with sudoku: `https://..../#,,,,5,8,7,,4,9,,7,3,,,,,,,8,,,,,,,2,,,,,7,,,,,,5,,9,3,6,,,8,,6,,8,,,9,3,5,,,6,4,8,3,5,,,,,,,,,2,8,,5,,,,1,,,,3`

I can get this value with `window.location.hash.substring(1);` but I can't insert this values into the board: `Uncaught TypeError: opts is undefined`. Must I convert this string to object? How? Because sudoku from `mySudokuJS.getBoard()` is object.

Or... I can insert values into the board but `user finished board!` when I write one number anywhere.

**Comment by vsevjednom-cz** [comment]
Combination with PHP solved it.

Url must starts with ?, not with #.

`https://.../?,,7,3,8,,2,9,,,,,,,9,8,6,3,8,,,,,1,4,,,,,,8,,7,1,3,,,,,,,4,,7,9,,7,,6,,,,,8,,,8,,,,,,,1,,,7,4,,,,,7,,9,1,2,,,,`

And after that:
```
var hash = ['.$_SERVER['QUERY_STRING'].'undefined];
mySudokuJS.setBoard(hash);
```
