### ISSUE TITLE
How to set the board from window.location.hash?

### ISSUE THREAD

**Issue by vsevjednom-cz** [pocketjoso/sudokuJS#8]
I wanna create url with generated sudoku and use only Javascript. I can create url like this: `https://.../#3,,,8,,,1,9,7,,,,,,,,,,,8,,,,6,3,4,2,,3,,5,2,8,,,6,1,2,,,,,,,,6,,9,4,,,,8,,,,6,,8,1,7,,,,,,,,,4,,,7,,,,6,,8,,1,` but Javascript thinks that it's string, not array. I tried for example this `hash = Array.from(window.location.hash); mySudokuJS.setBoard(hash);`. Also I tried create empty array, then insert values by `push`.

It works in PHP like this: `https://.../?3,,,8,,,1,9,7,,,,,,,,,,,8,,,,6,3,4,2,,3,,5,2,8,,,6,1,2,,,,,,,,6,,9,4,,,,8,,,,6,,8,1,7,,,,,,,,,4,,,7,,,,6,,8,,1,` and then `var hash = ['.$_SERVER['QUERY_STRING'].']; mySudokuJS.setBoard(hash);`. Is possible to do it only in Javascript?

**Comment by pocketjoso** [comment]
Once you've grabbed the part of the url that contains your comma separated sudoku board, you can parse it with [String.split](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split), using `,` as the separator, like this:
`window.location.hash.split(',')`.

As a side note, it seems more appropriate to use a query parameter than a hash for this. I.e. `htps://.../?board=3,,,8,,,1,9,7,,,,,,,,,,,8,,,,6,3,4,2,,3,,5,2,8,,,6,1,2,,,,,,,,6,,9,4,,,,8,,,,6,,8,1,7,,,,,,,,,4,,,7,,,,6,,8,,1,`.

**Comment by vsevjednom-cz** [comment]
Wow, thank you for fast answer!

Yep, I tried `split` too. It works but `solveStep` and `solveAll`  not works. It maybe thinks that sudoku is solved..? How can I set sudoku like unsolved?

**Comment by vsevjednom-cz** [comment]
`var hash = window.location.hash.substring(1).split(","); mySudokuJS.setBoard(hash);` = `solveStep` and `solveAll` does not work.
`var hash = [
	, , ,4, ,8, ,2,9
	, , , , , , , , ,4
	,8,5, , ,2, , , ,7
	, , ,8,3,7,4,2, ,
	, ,2, , , , , , ,
	, , ,3,2,6,1,7, ,
	, , , , ,9,3,6,1,2
	,2, , , , , ,4, ,3
	,1,3, ,6,4,2, ,7,undefined
]; mySudokuJS.setBoard(hash);` = works.

**Comment by pocketjoso** [comment]
Could you try replacing the empty strings with `undefined`?
`window.location.hash.substring(1).split(",").map(v => v === '' ? undefined : v)`;

**Comment by vsevjednom-cz** [comment]
I'm trying. `boardErrorFn` right now when I try to call `solveStep` and `solveAll` 😨.

**Comment by pocketjoso** [comment]
ah. You also need to parse the numbers as such - right now they are strings. Use `parseInt` for this:

`window.location.hash.substring(1).split(",").map(v => v === '' ? undefined : parseInt(v, 10));`

**Comment by vsevjednom-cz** [comment]
Thank you but problem is still the same: `boardErrorFn` 😓.

**Comment by vsevjednom-cz** [comment]
Oh. There was a problem in my code somewhere. I don't know where but it works right now. Thank you, thank you, thank you!
